---
abstract: 'Import vCards for use by App::Office::Contacts'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::Pod: 1.41
  Test::Simple: 0.94
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Office-Contacts-Import-vCards
provides:
  App::Office::Contacts::Import::vCards:
    file: lib/App/Office/Contacts/Import/vCards.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::Controller:
    file: lib/App/Office/Contacts/Import/vCards/Controller.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::Controller::Import:
    file: lib/App/Office/Contacts/Import/vCards/Controller/Import.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::Controller::Initialize:
    file: lib/App/Office/Contacts/Import/vCards/Controller/Initialize.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::Util::Config:
    file: lib/App/Office/Contacts/Import/vCards/Util/Config.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::Util::vCards:
    file: lib/App/Office/Contacts/Import/vCards/Util/vCards.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::View:
    file: lib/App/Office/Contacts/Import/vCards/View.pm
    version: 1.11
  App::Office::Contacts::Import::vCards::View::vCards:
    file: lib/App/Office/Contacts/Import/vCards/View/vCards.pm
    version: 1.11
requires:
  App::Office::Contacts: 1.1
  Moose: 0.98
  Text::DoubleMetaphone: 0.07
  Text::GenderFromName: 0.33
  Text::vFile::toXML: 0.04
  XML::Handler::YAWriter: 0.23
  XML::SAX: 0.96
  XML::SAX::Base: 1.02
  namespace::autoclean: 0.09
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.11
